all:
  hosts:
    node1:
      ansible_host: 
      ip:
      access_ip: 
    node2:
      ansible_host: 
      ip:
      access_ip:
    node3:
      ansible_host: 
      ip:
      access_ip:  
  children:
    kube_control_plane:
      hosts:    
        node2:
    kube_node:
      hosts:
        node3:
    etcd:
      hosts:
        node2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
      
